### ISSUE TITLE
create resources/lastdeath.json if it doesn't exist

### ISSUE THREAD

**Issue by laneatomic** [small-worlds/discordbot#5]
I noticed on bot startup that I forgot to copy the resources over from the old install. See below for stacktrace.

```
[ERROR : ct-5 @ 2016-10-05 20:48:34.296] Exception: #<Errno::ENOENT: No such file or directory @ rb_sysopen - resources/lastdeath.json>
[ERROR : ct-5 @ 2016-10-05 20:48:34.297] /home/lane/discordbot/app/custom_commands.rb:43:in `read'
[ERROR : ct-5 @ 2016-10-05 20:48:34.297] /home/lane/discordbot/app/custom_commands.rb:43:in `block in <module:CustomCommands>'
[ERROR : ct-5 @ 2016-10-05 20:48:34.297] /home/lane/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/discordrb-2.1.3/lib/discordrb/commands/parser.rb:85:in `call'
[ERROR : ct-5 @ 2016-10-05 20:48:34.297] /home/lane/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/discordrb-2.1.3/lib/discordrb/commands/command_bot.rb:167:in `execute_command'
[ERROR : ct-5 @ 2016-10-05 20:48:34.297] /home/lane/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/discordrb-2.1.3/lib/discordrb/commands/command_bot.rb:182:in `simple_execute'
[ERROR : ct-5 @ 2016-10-05 20:48:34.297] /home/lane/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/discordrb-2.1.3/lib/discordrb/commands/command_bot.rb:270:in `block in execute_chain'
```

**Comment by laneatomic** [comment]
This should now also create resources/alldeaths.json too.
